Ceci est une pré-analyse rapide des données. uniquement de l'exploration et du prédictif. on joindra nos analyse pour voir de quel coté on va ensemble finalement.

In [2]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

sns.set_theme(style="white", context="notebook")

SEED = 42

Chargement des données

In [5]:
df = pd.read_csv("../../../data/regularite-mensuelle-tgv-aqst.csv",sep=";")

on a quoi dedans ??

In [8]:
df.describe()

,Durée moyenne du trajet,Nombre de circulations prévues,Nombre de trains annulés,Commentaire annulations,Nombre de trains en retard au départ,Retard moyen des trains en retard au départ,Retard moyen de tous les trains au départ,Commentaire retards au départ,Nombre de trains en retard à l'arrivée,Retard moyen des trains en retard à l'arrivée,...,Nombre trains en retard > 15min,Retard moyen trains en retard > 15 (si liaison concurrencée par vol),Nombre trains en retard > 30min,Nombre trains en retard > 60min,Prct retard pour causes externes,Prct retard pour cause infrastructure,Prct retard pour cause gestion trafic,Prct retard pour cause matériel roulant,Prct retard pour cause gestion en gare et réutilisation de matériel,"Prct retard pour cause prise en compte voyageurs (affluence, gestions PSH, correspondances)"
count,12544.000000,12544.000000,12544.000000,0.0,12544.000000,12544.000000,12544.000000,0.0,12544.000000,12544.000000,...,12544.000000,12544.000000,12544.000000,12544.000000,12544.000000,12544.000000,12544.000000,12544.000000,12544.000000,12544.000000
mean,170.628508,272.623884,8.407685,NaN,86.219866,12.499854,3.175135,NaN,38.243304,35.471909,...,27.576531,36.739460,13.025989,5.370615,21.897002,21.491158,20.118126,18.993447,7.762730,7.581653
std,87.730733,183.559230,22.089205,NaN,88.428503,11.660090,5.054562,NaN,31.826539,15.605191,...,23.316212,19.388035,12.684545,6.250032,16.068989,14.914196,14.709970,13.564449,8.682545,9.451102
min,0.000000,0.000000,0.000000,NaN,0.000000,0.000000,-229.269444,NaN,0.000000,-40.109259,...,0.000000,-4.000000,-44.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,99.000000,151.000000,0.000000,NaN,22.000000,6.346596,1.226076,NaN,16.000000,25.958062,...,11.000000,28.732917,4.000000,1.000000,10.714286,11.538462,10.000000,10.000000,0.000000,0.000000
50%,163.000000,230.000000,2.000000,NaN,52.000000,10.560933,2.368000,NaN,30.000000,33.777423,...,22.000000,38.004578,10.000000,3.000000,19.642857,20.000000,18.461538,17.142857,5.882353,5.031800
75%,223.000000,362.000000,7.000000,NaN,126.000000,16.101225,4.031985,NaN,52.000000,42.776681,...,37.000000,47.501389,18.000000,7.000000,30.252101,29.268293,28.571429,25.617573,11.398558,11.111111
max,786.000000,1100.000000,297.000000,NaN,596.000000,316.188095,115.047390,NaN,376.000000,299.600000,...,312.000000,299.600000,202.000000,77.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000

In [11]:
df.shape

(12544, 26)

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12544 entries, 0 to 12543
Data columns (total 26 columns):
 #   Column                                                                                       Non-Null Count  Dtype
---  ------                                                                                       --------------  -----
 0   Date                                                                                         12544 non-null  str
 1   Service                                                                                      12544 non-null  str
 2   Gare de départ                                                                               12544 non-null  str
 3   Gare d'arrivée                                                                               12544 non-null  str
 4   Durée moyenne du trajet                                                                      12544 non-null  int64
 5   Nombre de circulations prévues                                                               12544 non-null  int64
 6   Nombre de trains annulés                                                                     12544 non-null  int64
 7   Commentaire annulations                                                                      0 non-null      float64
 8   Nombre de trains en retard au départ                                                         12544 non-null  int64
 9   Retard moyen des trains en retard au départ                                                  12544 non-null  float64
 10  Retard moyen de tous les trains au départ                                                    12544 non-null  float64
 11  Commentaire retards au départ                                                                0 non-null      float64
 12  Nombre de trains en retard à l'arrivée                                                       12544 non-null  int64
 13  Retard moyen des trains en retard à l'arrivée                                                12544 non-null  float64
 14  Retard moyen de tous les trains à l'arrivée                                                  12544 non-null  float64
 15  Commentaire retards à l'arrivée                                                              698 non-null    str
 16  Nombre trains en retard > 15min                                                              12544 non-null  int64
 17  Retard moyen trains en retard > 15 (si liaison concurrencée par vol)                         12544 non-null  float64
 18  Nombre trains en retard > 30min                                                              12544 non-null  int64
 19  Nombre trains en retard > 60min                                                              12544 non-null  int64
 20  Prct retard pour causes externes                                                             12544 non-null  float64
 21  Prct retard pour cause infrastructure                                                        12544 non-null  float64
 22  Prct retard pour cause gestion trafic                                                        12544 non-null  float64
 23  Prct retard pour cause matériel roulant                                                      12544 non-null  float64
 24  Prct retard pour cause gestion en gare et réutilisation de matériel                          12544 non-null  float64
 25  Prct retard pour cause prise en compte voyageurs (affluence, gestions PSH, correspondances)  12544 non-null  float64
dtypes: float64(13), int64(8), str(5)
memory usage: 2.5 MB

In [12]:
df.head()

,Date,Service,Gare de départ,Gare d'arrivée,Durée moyenne du trajet,Nombre de circulations prévues,Nombre de trains annulés,Commentaire annulations,Nombre de trains en retard au départ,Retard moyen des trains en retard au départ,...,Nombre trains en retard > 15min,Retard moyen trains en retard > 15 (si liaison concurrencée par vol),Nombre trains en retard > 30min,Nombre trains en retard > 60min,Prct retard pour causes externes,Prct retard pour cause infrastructure,Prct retard pour cause gestion trafic,Prct retard pour cause matériel roulant,Prct retard pour cause gestion en gare et réutilisation de matériel,"Prct retard pour cause prise en compte voyageurs (affluence, gestions PSH, correspondances)"
0,2018-01,National,BORDEAUX ST JEAN,PARIS MONTPARNASSE,141,870,5,NaN,289,11.247809,...,110,6.511118,44,8,36.134454,31.092437,10.924370,15.966387,5.042017,0.840336
1,2018-01,National,LE MANS,PARIS MONTPARNASSE,56,406,1,NaN,213,8.479969,...,32,5.363539,9,4,20.000000,35.000000,16.666667,16.666667,8.333333,3.333333
2,2018-01,National,PARIS MONTPARNASSE,LA ROCHELLE VILLE,166,226,0,NaN,21,6.239683,...,11,2.938053,6,1,22.222222,27.777778,16.666667,16.666667,5.555556,11.111111
3,2018-01,National,PARIS MONTPARNASSE,NANTES,124,508,3,NaN,71,7.235211,...,39,5.292211,18,8,33.333333,22.222222,16.666667,20.370370,5.555556,1.851852
4,2018-01,National,POITIERS,PARIS MONTPARNASSE,94,472,4,NaN,224,6.784673,...,42,4.882372,10,0,15.789474,45.614035,19.298246,15.789474,1.754386,1.754386

Sur un premier coup d'oeil, on peut voir : 

1) Ce sont des statistiques de régularité mensuelles pour diverses lignes (TODO vérifier qu'il ne manque pas des mois ou des lignes)

2) on a beaucoup de variables (26). il semble important de se concentrer sur celles importantes pour la question qu'on aura choisie. En plus elles ne 
s'affichent pas toutes dans notre notebook avec head ou describe !

3) certaines colonnes doivent être retypée car 
- float64 mais ne l'étant pas. ex : "commentaire annulations" au lieu de str
- str qui doivent devenir category. ex : Service (nationnal / internationnal / ...)
- les gares aussi : par ailleur on devrait réunir les colonnes gare de départ et d'arrivée en une seule (concat) et ensuite seulement transformer en category
- Date est une str, il faut la mettre en date

4) on peut déjà voir qu'il y a des données étranges :
- divers retard moyen, ou nombre de train : le min est négatif parfois fortement => à nettoyer proprement (impact ?)
- des NaN sur des commentaires (a priori on ne gardera pas les colonnes de commentaires)



=> donc la premiere conclusion est :
- se mettre d'accord sur un sujet. certains sujet sont-ils impossibles avec ces données ou peut-on faire confiance ?
- on se met daccord sur les colonnes à conserver.
- quelle premieres idées sur le produit final pour nos utilisateurs ? 
- ensuite quelqu'un s'occupe de nettoyer / typer notre df.
- analyse séparée des données dans divers poc ? et on réunis le tout ?